### PR TITLE
Togglz Rest API module proposal

### PR DESCRIPTION
**Pull request by fabito**
This is an initial draft proposal for a Togglz REST API module.
It basically contains a Servlet that once installed exposes a FeatureToggle resource containing the following operations:

| Description | Verb | Response Codes | Content Type | Sample Curl Commands |
| --- | --- | --- | --- | --- |
| Lists all feature toggles | GET | 200 | application/json | curl 'https://togglz-dot-gae-skeletons.appspot.com/featuretoggles' -H 'content-type: application/json'  --compressed |
| Gets a specific feature toggle (by name) | GET | 200, 404 | application/json | curl 'https://togglz-dot-gae-skeletons.appspot.com/featuretoggles/FEATURE_THREE'  -H 'content-type: application/json' --compressed |
| Updates a specific feature toggle (by name) | PUT | 200, 404 | - | curl 'http://togglz-dot-gae-skeletons.appspot.com/featuretoggles/FEATURE_ONE' -X PUT -H 'Content-Type: application/json'  --data-binary $'{ \'enabled\' : false, \'name\' : \'FEATURE_ONE\'}' --compressed |

The code still need some improvements but I decided to create this pull request to foment a discussion about the design and the real usefulness of this module.
Some design decisions (so far):
1. Opted to leave security out of the module's scope - users can secure the resource as they wish.
2. **json-smart** library for JSON (des)serialization - lightweight and fast
3. Unit testing with **jetty-servlet-tester** (still not familiar with Arquillian)
4. Pure servlet implementation (not using JAX-RS)

Check it out here:  [https://togglz-dot-gae-skeletons.appspot.com](https://togglz-dot-gae-skeletons.appspot.com/_ah/togglz/)

Sample curl commands:

``` shell
curl 'https://togglz-dot-gae-skeletons.appspot.com/featuretoggles' -H 'content-type: application/json'  --compressed

curl 'http://togglz-dot-gae-skeletons.appspot.com/featuretoggles/FEATURE_ONE' -X PUT -H 'Content-Type: application/json'  --data-binary $'{ \'enabled\' : false, \'name\' : \'FEATURE_ONE\'}' --compressed

curl 'https://togglz-dot-gae-skeletons.appspot.com/featuretoggles/FEATURE_THREE'  -H 'content-type: application/json' --compressed
```

### CODE REVIEW

**Comment by charithdesilva** [comment]
Hi folks - do you guys know where this feature headed? I'm in a need to provide ability to tweak features from a custom admin screen and looking to use a Rest API but I couldn't find artifacts on the main line.

**Comment by chkal** [comment]
This feature hasn't been merged yet. And if I remember correctly it still needs some polish and things have to be discussed.

So for now you will have to create you own REST endpoint. But that's actually very easy. You can basically call `FeatureContext.getFeatureManager()` to obtain the `FeatureManager` and then use it's public API to get and update the feature state.

**Comment by charithdesilva** [comment]
Thanks @chkal for prompt response.

**Comment by compwron** [comment]
I would really like this branch to be merged. Is anyone working on this? If not, I can volunteer to help (over a timescale of weeks, not days). I work in java and with togglz for work.

**Comment by chkal** [comment]
Hi @compwron. Thanks for your interest in helping getting this one merged. I saw increasing interest for this in the last weeks.

I guess we have to discuss some key constraints and requirements first. Especially about authentication.

Perhaps we should discuss this on the mailing list first?!?

**Comment by atlanteh** [comment]
Any update?

**Comment by dougtweedy** [comment]
Any new updates on this? Looks promising for auditing.

**Comment by hennr** [comment]
This PR dates back to April 2014 and saw last updates in 2017.
Any hard feelings against simply closing it?

**Comment by fabito** [comment]
Not at all.

**Comment by hennr** [comment]
Perfect, thanks for your quick response @fabito !

**Pull request closed without merging**
