### PR TITLE
Implemented more fine-grained Spring Boot starters containing only required dependencies - Spring Boot 3

### PR DESCRIPTION
**Pull request by Harmelodic**
It's basically this PR: https://github.com/togglz/togglz/pull/888

but refactored slightly to:
- Use Spring Boot 3 / Jakarta / Spring 6
- Have Spring Boot Dependencies BOM defined in the parent pom (`./spring-boot/pom.xml`) rather than in each child pom (`./spring-boot/*/pom.xml`).
- Not make changes to EditorConfig (keeping `pom.xml` files as 4-space indentation)

### CODE REVIEW

**Comment by Harmelodic** [comment]
Re-pushed because in the #888 PR the `./spring-boot/starter/src/main/resources/META-INF/spring.factories` was moved into the `./spring-boot/autoconfigure` module.

But since `spring.factories` was replaced with `.imports` files (and some other Java Classes were created since then in the `./spring-boot/starter` module, I needed to move those over to the `./spring-boot/autoconfigure` module, as was done in #888.

**Comment by Harmelodic** [comment]
Re-pushing again, to move the `spring-security-test` dependency from `./spring-boot/starter` to `./spring-boot/autoconfigure`.

**Comment by Harmelodic** [comment]
Okay, I think I'm done.

**Comment by Harmelodic** [comment]
I was not done.
As part of the move over of files from `starter` to `autoconfigure` I'd removed some `json` files used in `test/resources`.

**Comment by Harmelodic** [comment]
Finally, after fixing the CodeQL GitHub Action.
It builds!! 🎉

**Comment by Harmelodic** [comment]
Can we... merge? 👀 ❤️

**Comment by Harmelodic** [comment]
@bennetelli - Can we... merge? 👀 ❤️

**Comment by bennetelli** [comment]
Hey @Harmelodic :) I am back from vacation. Will merge it today.

**Comment by Harmelodic** [comment]
Heyo, pinging again as it's been a while.

Still really wanting a Spring Boot 3 release and if this is the last thing to go in, then it'd be great to get this merged and the 4.0.0 version to be released!

**Comment by bennetelli** [comment]
I will merge this either today or tomorrow. Don't know if I will have enough time today.
Btw: you could still use the 4.0.0-Milestone release which contains Spring Boot already.

**Comment by Harmelodic** [comment]
Thanks! Sadly (but also IMO, not so sadly) we can't/won't use beta or milestone releases in production for our projects.

Looking forward to the release! 😄 Thanks again for the update.

**Comment by bennetelli** [comment]
> Thanks! Sadly (but also IMO, not so sadly) we can't/won't use beta or milestone releases in production for our projects.
> 
> Looking forward to the release! smile Thanks again for the update.

I could also call this release an non-milestone if it better fits your process :-D even with a -M postfix, the release is already in use at a lot of companies and isn't that unstable as you think. Anyway. I will merge this and release 4.0.0 without postfix.

**Comment by Harmelodic** [comment]
> I could also call this release an non-milestone if it better fits your process :-D

It's not a stability thing, as I've already tested the milestone on an big project, and it worked nicely 😅 
Without revealing too much, it's more of a bureaucracy / risk / policy / principle thing.

> Anyway. I will merge this and release 4.0.0 without postfix.

Yus, let's gooooooooo 🚀

**Comment by bennetelli** [comment]
still on it. will take a look at it together with another reviewer today.

**Comment by bennetelli** [comment]
we just fixed the conflicts in #888 (sorry.. I would like to merge Christian's PR as he worked on the restructuring for a long time and I would like to honor it).
I will compare your and this PR once again just to be sure and then merge and release it

**Pull request closed without merging**
