### PR TITLE
Use webjars for static js/css assets

### PR DESCRIPTION
**Pull request by dasniko**
This is a first draft, like discussed in #213. Please test it and give feedback!

### CODE REVIEW

**Comment by chkal** [comment]
Looks good to me. But I just checked the diff and didn't test it locally yet. WebJarAssetLocator is nice. Didn't know about this one.

The only downside I see with this PR is that we are basically dropping Servlet < 3.0 support. Not sure if it makes sense to still support Servlet 2.5, it just came to my mind while reading the diff. Any thoughts about that?

**Comment by dasniko** [comment]
Yes, you're right. Didn't consider this. Do you have an idea of how widely servlet 2.5 is still used?

Another downside came up to me this moring: we're relying on e.g. Bootstrap 3.x, but 4.x is just to release and it changes the structure/classes (don't know how much, didn't look into it yet). Having different Bootstrap versions for 3.x in the project is ok, just anyone wins and it'll work. But if a project pulls in a 4.x resource, our layout might crash!

**Comment by chkal** [comment]
> Yes, you're right. Didn't consider this. Do you have an idea of how widely servlet 2.5 is still used?

Good question. Not sure about that. One of the apps I'm maintaining is using JBoss 6.1.0 which for some reason doesn't support `META-INF/resources` correctly. I had to write a Servlet manually which does what the spec actually requires. However, I would be fine with dropping support for Servlet 2.5. Libraries dropping support for old spec versions are a nice way to force users to update their app servers. :-)

> Another downside came up to me this moring: we're relying on e.g. Bootstrap 3.x, but 4.x is just to release and it changes the structure/classes (don't know how much, didn't look into it yet). Having different Bootstrap versions for 3.x in the project is ok, just anyone wins and it'll work. But if a project pulls in a 4.x resource, our layout might crash!

Agreed! One way to work around this would be to shade the webjar, but I'm not sure if this is a good thing to do.

**Comment by dasniko** [comment]
It will definitely break our layout, I just did a quick test. :-(

Shading would make no difference from the current solution, to have the distinct resources packed and delivered with the console. Shading would also lead to duplicate resources if someone uses another Bootstrap library.

So, I'm voting for dropping this PR and closing #213 for now, as it might lead to too much trouble/errors.

**Comment by chkal** [comment]
I agree. Thanks anyway for prototyping this. At least we all know about `WebJarAssetLocator` now. ;-)

**Pull request closed without merging**
