### PR TITLE
Google Cloud Storage state repository

### LINKED ISSUE #599: [Feature] Support GCP Cloud Storage as State Repository
Hi folks,

I would love to see [Google Cloud Storage](https://cloud.google.com/storage) as a state repository (as a GCP pendant to AWS S3). 
Open for a PR?

### PR DESCRIPTION
**Pull request by splieth**
Adds support for [Google Cloud Storage](https://cloud.google.com/storage) as state repository. Closes #599.

### CODE REVIEW

**Comment by splieth** [comment]
@bennetelli can you have a brief look into this?

**Comment by bennetelli** [comment]
Oh, sorry. Just read your message @splieth. Yes, I will take a look at it today after my meetings.

**Review by bennetelli — APPROVED** [review]

**Comment by bennetelli** [comment]
@splieth I just build release 3.0.0. It's currently in the sync process of sonatype. Should be available within the next hours.

**Comment by bennetelli** [comment]
Thanks for your PR :)

**Comment by splieth** [comment]
> @splieth I just build release 3.0.0. It's currently in the sync process of sonatype. Should be available within the next hours.

Thanks man, very cool!

> Thanks for your PR :)

Always happy to! :)

**Pull request merged**
