### PR TITLE
Implemented @DefaultActivationStrategy feature

### PR DESCRIPTION
**Pull request by KaiHofstetter**
Hi Christian,

just implemented `@DefaultActivationStrategy` feature, like discussed...

    public enum MyFeatures implements Feature {

        @EnabledByDefault
        @DefaultActivationStrategy(
            id = UsernameActivationStrategy.ID,
            parameters = {
                @ActivationParameter(name = UsernameActivationStrategy.PARAM_USERS, value = "person1,ck,person2")
            }
        )
        FEATURE_ONE;

    }

Thanks,
Kai

### CODE REVIEW

**Comment by KaiHofstetter** [comment]
I just saw that I accidentally commited my pom.xml changes.
I had problems running `mvn -DJBOSS_REPO=true clean install`. 
The bundlor maven plugin stopped with a `NoClassDefFoundError`:

    [INFO] --- org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor (bundlor) @ togglz-project ---
    [WARNING] Error injecting: org.eclipse.virgo.bundlor.maven.plugin.BundlorMojo
    java.lang.NoClassDefFoundError: org/eclipse/virgo/bundlor/support/manifestwriter/ManifestWriterFactory

I had to add following dependencies to the bundlor maven plugin:

    ...
    <plugin>
        <groupId>org.eclipse.virgo.bundlor</groupId>
        <artifactId>org.eclipse.virgo.bundlor.maven</artifactId>
        ...
        <dependencies>
            <dependency>
                <groupId>org.eclipse.virgo.bundlor</groupId>
                <artifactId>org.eclipse.virgo.bundlor</artifactId>
                <version>1.1.2.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.virgo.bundlor</groupId>
                <artifactId>org.eclipse.virgo.bundlor.blint</artifactId>
                <version>1.1.2.RELEASE</version>
            </dependency>
        </dependencies>
    </plugin>
    ...
    
It does not surprise me, that it did not compile, since the pom.xml of the bundlor maven plugin uses the scope `provided` for those two dependencies:
    
    ...
    <dependency>
        <groupId>org.eclipse.virgo.bundlor</groupId>
        <artifactId>org.eclipse.virgo.bundlor</artifactId>
        <version>${project.version}</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.eclipse.virgo.bundlor</groupId>
        <artifactId>org.eclipse.virgo.bundlor.blint</artifactId>
        <version>${project.version}</version>
        <scope>provided</scope>
    </dependency>
    ... 

I don't seem to be the only person, who had that problem: https://github.com/togglz/togglz/issues/129

Regards,
Kai

**Comment by chkal** [comment]
Awesome! Thanks a lot. I'll try to find some time in the next days to review that patch. Unfortunately I'm very busy at the moment. So it may take some days..

**Comment by chkal** [comment]
Thanks a lot. This looks great! I just added some more javadocs for the annotations. And I set a default value for the parameters so that users can omit the parameters if they don't want to set any (Not sure if this happens though). 

See: ac6d5fdf8944791922c240d9139033410271d21e

Thanks again for the contribution!

**Comment by KaiHofstetter** [comment]
No problem. Thank you for accepting my pull request!

**Pull request merged**
