### PR TITLE
Generic enums support

### PR DESCRIPTION
**Pull request by ruifigueira**
First attempt, basically copy and adapting existing code, for instance, `EnumBasedFeatureProvider`.

Check #293 for more details.

### CODE REVIEW

**Comment by BeneStem** [comment]
Neat! I will try that with Kotlin today. Thank you so much!

**Comment by BeneStem** [comment]
What can I do to help you merge this PR?

**Comment by ruifigueira** [comment]
@BeneStem, I just added a kotlin module, as well as spring boot support for generic enums. Check my commits.

I still need to test most of the things, for the time being I'm just throwing code to check if kotlin support is actually feasible.

**Comment by BeneStem** [comment]
@ruifigueira Yeah I saw that and thought the same (code throwing). I am currently trying to make your code changes work in my project as well and I am getting good results ;)

**Comment by ruifigueira** [comment]
That's great!

@chkal, maybe we can include kotlin support in 2.7.0? If that's the case, it's a matter of polishing this code, as well as create more JUnit tests (for now, there are a couple things for the generic enum part) and documenting it

**Comment by BeneStem** [comment]
@ruifigueira have a look at https://github.com/togglz/togglz/pull/293#issuecomment-408679245 for my implementation.

I don't think we actually need the Kotlin extension you wrote :)

**Comment by chkal** [comment]
Sure. I would be fine with including this in 2.7.0. As long as it integrates well with the other parts of Togglz. However, I still think that it would be great to get some feedback from the Kotlin guys on whether the issue you are running into is intended or if it is simply a bug that can be fixed.

**Comment by BeneStem** [comment]
@chkal I here you. This feedback from them would be great.

You can find my whole wrapper implementation here https://github.com/e-breuninger/spring-boot-starter-breuninger/tree/master/spring-boot-starter-breuninger-togglz/src/main/java/com/breuninger/boot/togglz

**Comment by ruifigueira** [comment]
@BeneStem, I'm aware that the kotlin extension code is not needed, but adding some extension methods for enum classes or even `Feature` can help people that uses kotlin because they don't need to keep declaring an `isActive` method, for instance.

**Comment by BeneStem** [comment]
Yeah sure. Good thinking :)

I was just happy that you helped me fix my problem and wanted to be at least a bit helpful. :S

**Comment by ruifigueira** [comment]
@BeneStem, but you made me realize that we actually don't need kotlin extension methods, they can pollute other enum objects, and that's not such a good thing.

For now, I'm happy with the `GenericEnumFeatureProvider`, and I think that's something we can easily merge into togglz, and already provides everything you need to use kotlin enums as "features".

Regarding kotlin utilities, I need to think a little bit more.

**Comment by BeneStem** [comment]
Hey there. Yes. That is exactly what I was thinking about ;)

**Comment by bennetelli** [comment]
Hi there,
I think we don't need this PR anymore as we already have a kotlin wrapper included in togglz?

**Pull request closed without merging**
