### PR TITLE
Added easy way of disabling security of admin console

### PR DESCRIPTION
**Pull request by marceloverdijk**
Added easy way of disabling security of admin console.
This is quite useful if security of the console is done via other security system used by application.

### CODE REVIEW

**Comment by marceloverdijk** [comment]
See https://github.com/togglz/togglz/issues/151

**Comment by chkal** [comment]
Looks good. Thanks a lot.

**Comment by marceloverdijk** [comment]
Thx!

**Comment by marceloverdijk** [comment]
Btw when do you think you will release 2.3.0? With these and the Spring core changes this would be useful.

**Comment by chkal** [comment]
Not sure when 2.3.0 will be ready. I think that it would be good if more people would test your Spring Boot integration. So if anything comes up that would require more changes in Togglz itself, we could get them in quickly.

Not sure what your plans for the Boot Integration module are. But in theory it could become a Togglz module. Or do you want to keep it standalone?

**Comment by marceloverdijk** [comment]
@chkal No I don't want to keep it standalone. However I would prefer it to be merged in directly to Spring Boot itself. I'm in talks with the Boot devs about that.
If they don't want to include it in Boot I think best option is to make it a Togglz module.

**Comment by chkal** [comment]
Ok, sure. I just wanted to emphasize that I would of cause be happy to see it as a Togglz module. However, integrating it into Spring Boot directly may be even better. :smile:

**Pull request merged**
