### PR TITLE
Align togglz with virtual threads

### PR DESCRIPTION
**Pull request by wyhasany**
Calling togglz from virtual threads causing pinning to the platform (aka carrier thread):
```
Thread[#457,ForkJoinPool-1-worker-13,5,CarrierThreads]
    java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:183)
    java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:393)
    java.base/java.lang.VirtualThread.parkNanos(VirtualThread.java:621)
    java.base/java.lang.System$2.parkVirtualThread(System.java:2652)
    java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:67)
    java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:267)
    java.base/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1866)
    java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
    java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
    java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
    java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
    io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:83)
    io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:244)
    io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75)
    io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
    jdk.proxy2/jdk.proxy2.$Proxy182.hgetall(Unknown Source)
    java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    java.base/java.lang.reflect.Method.invoke(Method.java:580)
    io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:215)
    io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
    jdk.proxy2/jdk.proxy2.$Proxy182.hgetall(Unknown Source)
    org.togglz.redis.RedisLettuceStateRepository.getFeatureState(RedisLettuceStateRepository.java:52)
    org.togglz.core.repository.cache.CachingStateRepository.reloadFeatureState(CachingStateRepository.java:81) <== monitors:1
    org.togglz.core.repository.cache.CachingStateRepository.getFeatureState(CachingStateRepository.java:73)
    org.togglz.core.manager.DefaultFeatureManager.isActive(DefaultFeatureManager.java:67)
```
To avoid it I replaced synchronized blocks with ReentrantLock.
https://openjdk.org/jeps/444

### CODE REVIEW

**Comment by wyhasany** [comment]
@bennetelli  can you take a look?

**Comment by wyhasany** [comment]
@bennetelli I'm going to add another commit here to add async fetch from remote repo to not affect latency of requests which checks feature flags

**Comment by wyhasany** [comment]
@bennetelli I added part of code responsible for fetching asynchronously feature flags, feel free to review the code :)

**Comment by wyhasany** [comment]
@bennetelli kindly remainder 🙏🏼

**Comment by wyhasany** [comment]
@bennetelli can you take a look on this PR? 🥺

**Review by bennetelli — APPROVED** [review]

**Comment by bennetelli** [comment]
Thanks for your PR @wyhasany . I am working at a second notebook I got from a customer.. sorry, did not watch github on my other notebook the last months..

**Pull request merged**
