### PR TITLE
Added Togglz - Cassandra integration

### PR DESCRIPTION
**Pull request by artur-tamazian**
StateRepository implementation that uses Astyanax to store features’
states in Cassandra.

### CODE REVIEW

**Comment by chkal** [comment]
Awesome! Thanks a lot. I hope I'll fine some time at the weekend to review it.

**Comment by chkal** [comment]
Thanks a lot. This module looks good. I cannot give it a test drive but I guess you did. ;)

Many many thanks for this contribution.

**Comment by chkal** [comment]
BTW: I'm not very faimilar with Cassandra. Is there a way to add unit/integration tests for this repository?

**Comment by artur-tamazian** [comment]
I can try to write a test using https://github.com/jsevellec/cassandra-unit. WIll try to do it this week

**Comment by chkal** [comment]
Great! That would be awesome! ;)

**Pull request merged**
