### PR TITLE
Use new java language feature

### PR DESCRIPTION
**Pull request by Pryanic**

### CODE REVIEW

**Comment by Pryanic** [comment]
@chkal Please look at this PR

**Comment by Pryanic** [comment]
Just a littel thank you for a lot that you do in your helpfull project

**Comment by neocotic** [comment]
This PR is a bit confusing. The title suggests adding/utilizing new Java features, however, the changes appear to be mainly minor refactors:

* Removal of redundant genetics
* Removal of unused imports
* Changing case of long indicators

What new Java feature are you using? The improved genetic inference? If so, I would just create a PR for each individual refactor and submit them independently as to avoid doing too much wide spread refactoring under a single PR.

**Comment by chkal** [comment]
Hey @Pryanic. Thanks for the PR. I agree with @neocotic that one commit or one PR per change type would be better and easier to review.

However, your PR also breaks the tests. Looks like you removed an import which actually wasn't unused. :-)

**Pull request closed without merging**
