### PR TITLE
Metadata in actuator and tests and fixes

### PR DESCRIPTION
**Pull request by ptriller**
Hello
I implemented integrating the MetaData into the actuator endpoint. (as mentioned [here](https://github.com/togglz/togglz/issues/870))
While doing that I found out that the error handling for the Web Endpoints was not optimal. The Actuator returned a 500 error when trying to set parameters with and illegal format. Since that is a client error and not a server error a 5xx error is inappropriate. For the JMX endpoint throwing an exception is probably ok, but for the web the correct HTTP status code would be better.

I added an `@EndpointWebExtension` to handle validation and errors properly in the HTTP case.
I also added some Integration Tests that test the actual Endpoints. I am not 100 % sure those are necessary, because now basically the same things are testet over 3 channels: JUNIT directly, HTTP and JMX. 

Let me know if I should keep the tests or reduce/remove some of them and if there are any issues with my implementation

### CODE REVIEW

**Comment by bennetelli** [comment]
hey @ptriller first of all, thank you very much for your PR :-) 
Basically it's looking good. I would like to bring together the FeatureEnumMetaData interface and the FeatureMetaData class in kotlin with your PR. Does it make sense to you to let your Metadata class implement the FeatureMetaData interface? Just took a brief look at it and I think these classes and interfaces somehow belong together and your metadata class should implement the interface. Does it make sense to you?

**Comment by ptriller** [comment]
> hey @ptriller first of all, thank you very much for your PR :-) Basically it's looking good. I would like to bring together the FeatureEnumMetaData interface and the FeatureMetaData class in kotlin with your PR. Does it make sense to you to let your Metadata class implement the FeatureMetaData interface? Just took a brief look at it and I think these classes and interfaces somehow belong together and your metadata class should implement the interface. Does it make sense to you?

Conceptually the contain the same data , however the `TogglzFeature` and `TogglzFeatureMetaData` are designed to serialize nicely into JSON without any further configuration.
If we add the Interface to the class it would start using `FeatureGroup` and `FeatureState` and both do not easily serialize into clean JSON.
Without adding a dependency to Jackson there is no way to configure how it would be serialized (as far as I know)

As the code is now `TogglzFeature` and `TogglzFeatureMetaData` are purely used as Containers for the data for the acutator endpoint and personally I do not think there is much to gain if we add the Interface. There is no functionality gained by using the `TogglzEndpoint` anywhere else in place of the `FeatureManager` directly. 
However I do not really have an overview over the architecture of Togglz, so if you think it would make things more consistent, I can try to add the Interface.

**Comment by hennr** [comment]
I will try to have a look tomorrow on this!

**Comment by hennr** [comment]
Hi @ptriller , thanks for the PR!

Did I understood it right, that the WebExtension will now handle all http requests and the TogglzEndpoint will handle stuff like JMX?

**Comment by ptriller** [comment]
> Hi @ptriller , thanks for the PR!
> 
> Did I understood it right, that the WebExtension will now handle all http requests and the TogglzEndpoint will handle stuff like JMX?

Correct, since the types need to be a bit different between those two you can make separate custom code for Web/JMX with this WebExtension

**Comment by hennr** [comment]
Works for me so far. I would merge it and add some more comments as wel as fixing the logging setup.

Fine for you, @bennetelli ?

I will be back online next monday.

**Comment by hennr** [comment]
@bennetelli , good to merge if the build was green?

**Comment by ptriller** [comment]
@bennetelli  I would fix it but I am confused. Throughout Master the slf4j version is 1.7.36 which would require a loggack version of 1.2.x however on your master the togglz.logback.version is set to 1.3.4. In other places this is ignored and set to 1.2.11 from somewhere
Should I override the global setting or fix it or wait for a fix ?

**Comment by hennr** [comment]
Hi @ptriller , that's probably my bad.
SLF4J 2.x was used along with logback 1.3.x but this didn't play well with spring-boot 2.x, so we rolled back to slf4j 1 leaving logback at 1.3.x.
With spring-boot 3.x support in place, we need to bump slf4j to 2.x and logack to something like 1.3.x or 1.4.x then.

I rolled back to logback 1.2.11 now, hope this helps with a green build.

**Comment by hennr** [comment]
Finally merged, thanks @ptriller 
Will try to get a new release out tomorrow.

**Pull request merged**
