### PR TITLE
fix Spring Boot auto configuration declaration to include TogglzEndpointAutoConfiguration (in addition to TogglzAutoConfiguration) (#455)

### PR DESCRIPTION
**Pull request by fabianlinz**
This should also solve #429

### CODE REVIEW

**Comment by fabianlinz** [comment]
#455

**Comment by bennetelli** [comment]
Thanks for your PR @fabianlinz :)

**Comment by rhanton** [comment]
Sorry, as someone trying to use togglz with a spring boot 1.x application, the fact that this was fixed in v2.9.0 at the same time support for spring-boot 1.x was removed is a pain. I'm going to try extending TogglzAutoConfiguration in my application to get it to run. 🤞

**Comment by hennr** [comment]
Sorry, yes, you have to.
We can't support multiple versions of spring-boot.

**Comment by bennetelli** [comment]
hm. Today Spring Boot 3 is going to be released. I think it's actually time to migrate from Spring Boot 1 to 2 at least. Sorry :(

**Pull request merged**
